FROM piern/msbuildtools2017:w2016f48

RUN mkdir "c:\\javainst\\"

COPY jdk-11.0.6_windows-x64_bin.exe "c:\\javainst"

RUN powershell start-process -filepath "C:\javainst\jdk-11.0.6_windows-x64_bin.exe -passthru -wait" -argumentlist "/s,INSTALLDIR=c:\Java\jdk-11.0.6,/L,install64.log"
RUN del c:\javainst\jdk-11.0.6_windows-x64_bin.exe

RUN setx /M PATH $($Env:PATH + ';c:\Java\jdk-11.0.6\bin') 

ENV JAVA_HOME 'c:\Java\jdk-11.0.6'

CMD [ "c:\\Java\\jdk-11.0.6\\bin\\java.exe", "-version"]


